name: alcocalc
description: A Dart library for precise alcohol dilution calculations, specifically designed for distillers and liqueur makers.
version: 1.0.0
publish_to: none
homepage: https://bitbucket.org/rebellion-rum/alcocalc

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  meta: ^1.11.0

dev_dependencies:
  test: ^1.25.0
  lints: ^3.0.0